services:
  mysql:
    image: mysql:8.0
    container_name: gym_mysql
    restart: always
    environment:
      MYSQL_DATABASE: gymregistration
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gym_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./GymRegistration
      dockerfile: Dockerfile
    container_name: gym_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gymregistration?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      JWT_SECRET: clave_secreta_muy_larga_para_que_funcione_bien_gymapp
      JWT_EXPIRATION: 86400000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gym_network

volumes:
  mysql_data:

networks:
  gym_network:
    driver: bridge
